spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: TzAi4BJWfrNX5kVjPxVh
            client-secret: 9ansr5LPE6
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: name
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

logging:
  level:
    root: info
    web: debug

lines:
  naver:
    url: https://openapi.naver.com
    client-secret: xgxam3osyo
    client-id: Ltr1_pDPga1mPjxgfhOr
  jwt-secret-key: temptUrl
  login-redirect-url: http://localhost:8080/login/oauth