POST http://localhost:8080/v1/lines
Authorization: beaerer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjYyNjUyMzkxLCJleHAiOjE2NjMwODQzOTF9.oGHTX29CEU0DSj6qzkvT1wrdY8Uhij3jaaIf769y5bU
Content-Type: application/json

{
  "book": {
    "title": "노인과 바다",
    "name": "헤르만헤세",
    "isbn": "9788955619256"
  },
  "content": "노인과 바다는 좋다",
  "ratio": "ONE_BY_ONE",
  "background": "#111111"
}

###
GET http://localhost:8080/v1/lines
Authorization: beaerer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiaWF0IjoxNjYyNjUyMzkxLCJleHAiOjE2NjMwODQzOTF9.oGHTX29CEU0DSj6qzkvT1wrdY8Uhij3jaaIf769y5bU