version: '2'

services:
  mysql:
    container_name: mysql8
    image: mysql:8
    volumes:
      - /root/lines/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test1234!
      - MYSQL_DATABASE=linesdb
    ports:
      - '3306:3306'
